### ISSUE TITLE
Fails to correctly minimize unit cell in some cases

### ISSUE THREAD

**Issue by Ash-Pera** [ftherrien/p2ptrans#10]
Hi Felix,
I was trying to run the naive path, so I just used the cells from the old output (I will use the simpler cells from the relaxation so it will not be a problem), and I noticed that it did not correctly make the structure into a minimal unit cell. The structure in question was:

> 1.0
  1.4831235021998115 -1.483318117615176 -1.4832521325148815
  1.6387510773074265e-05 -2.569427229255193 2.5693940861892988
  -6.293708258764652 -3.146895047240099 -3.1468950497351513
 Fe
6
direct
    1.1056164150354233   0.4999999999999999   0.1666666666666666
   -0.3944539401618030  -0.0000000000000000  -0.0000000000000000
    0.6055378322496290  -0.0000000000000001   0.3333333333333332
    0.1055663507713127   0.4999999999999999   0.4999999999999998
    0.1055175413165125   0.4999999999999998   0.8333333333333333
    0.6055731535163139  -0.0000000000000002   0.6666666666666666

I'll check that this is indeed the right structure, but...
Also, this might be a pylada issue? Might need to be looked at.

**Comment by ftherrien** [comment]
Yes you are right, it's because the tolerence on `pylada.crystal.primitive` is pretty strict right now. I will try to solve this soon.

**Comment by ftherrien** [comment]
This is solved by b0facc2d7992ffafeb34ec92475c180f23338760, but it will now create the same error as https://github.com/ftherrien/p2ptrans/issues/11
