### ISSUE TITLE
Pylada Error: Found translation but no primitive cell

### ISSUE THREAD

**Issue by Ash-Pera** [ftherrien/p2ptrans#11]
I was trying to run another transition, and got a pylada error:

> Traceback (most recent call last):
>   File "/u/st/am/aepera/.conda/envs/ash/bin/p2ptrans", line 160, in <module>
>     main()
>   File "/u/st/am/aepera/.conda/envs/ash/bin/p2ptrans", line 118, in main
>     tmat, dispStruc, vec_classes = findMatching(A, B, ncell, fileA=fileA, fileB=fileB,
>   File "/u/st/am/aepera/.conda/envs/ash/lib/python3.8/site-packages/p2ptrans/core.py", line 456, in findMatching
>     B = primitive(B, tol)
>   File "_primitive.pyx", line 116, in crystal._primitive.primitive
> pylada.error.RuntimeError: Found translation but no primitive cell
> 

I have attached the structures and error in question.
[pylada_err.zip](https://github.com/ftherrien/p2ptrans/files/4352076/pylada_err.zip)

**Comment by ftherrien** [comment]
The primitive function in pylada is a little bit too strict with tolerences which causes errors like that one. I will do a pull request in pylada that will hopefully solve this.

**Comment by ftherrien** [comment]
This should be solved via 07eeb287f3a74fa1a056a873a9c197d49396dd84
You will need to update pylada to see the changes.
