### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './fastoptimization.dat'

### ISSUE THREAD

**Issue by yanyuan55** [ftherrien/p2ptrans#22]
Hi,
After installing the p2ptrans, I tried to follow the Tutorials with a simple example. But the following error occurred. How to fix this?

(base) [yuayan1@spartan-login2 test_for_p2p]$ p2ptrans -I POSCAR_FCC -F POSCAR_BCCp2ptrans -I POSCAR_FCC -F POSCAR_BCC
 ________    _______  ________
|\   __  \  /  ___  \|\   __  \
\ \  \|\  \/__/|_/  /\ \  \|\  \
 \ \   ____\__|//  / /\ \   ____\
  \ \  \___|   /  /_/__\ \  \___|
   \ \__\     |\________\ \__\
    \|__|      \|_______|\|__|

__________TRANSFORMATIONS__________

=>Reading crystal analysis parameters<=

Making the cells primitive.
FCC structure (POSCAR_FCC) did not change. It has 1 atoms.
BCC structure (POSCAR_BCC) did not change. It has 1 atoms.

The optimization will be performed in the reversed direction.
Transition is *optimized* from BCC structure (POSCAR_BCC) to FCC structure (POSCAR_FCC)
Initial spacegroup in optimization: Im-3m (229)
Final spacegroup in optimization: Fm-3m (225)
Number of BCC structure (POSCAR_BCC) cells in sphere: 300
Number of FCC structure (POSCAR_FCC) cells in sphere: 300
Total number of atoms in each sphere: 300

Optimizing... (this may take several hours)
Check progress in ./progress.txt
Mapping time: 93.5170590877533
Trying to find periodicity directly (find_cell):
Traceback (most recent call last):
  File "/home/yuayan1/.local/lib/python3.8/site-packages/p2ptrans/core.py", line 711, in findMatching
    result = pickle.load(open(outdir+"/fastoptimization.dat","rb"))
FileNotFoundError: [Errno 2] No such file or directory: './fastoptimization.dat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuayan1/.local/bin/p2ptrans", line 183, in <module>
    main()
  File "/home/yuayan1/.local/bin/p2ptrans", line 130, in main
    tmat, dispStruc, vec_classes, _ = findMatching(A, B, ncell, fileA=fileA, fileB=fileB,
  File "/home/yuayan1/.local/lib/python3.8/site-packages/p2ptrans/core.py", line 714, in findMatching
    result = optimization(A, Acell, mulA, B, Bcell, mulB, ncell, filename, outdir, max_cell_size)
  File "/home/yuayan1/.local/lib/python3.8/site-packages/p2ptrans/core.py", line 574, in optimization
    print("Change in stretched dist: %f %%"(np.sum(la.norm(Bposst - Apos_map, axis=0)) - old_distp)/old_distp*100)
TypeError: 'str' object is not callable

**Comment by ftherrien** [comment]
Hi Yuan,

Thank you for your patience. I think I fixed what was causing the issue. Try reinstalling the new version of p2ptrans (2.0.6) and let me know if it fixes it.

**Comment by yanyuan55** [comment]
Hi Félix 

Thank you. It works now.
