### ISSUE TITLE
Issue in installation -  could not build wheel for p2ptrans

### ISSUE THREAD

**Issue by princego** [ftherrien/p2ptrans#30]
I am facing issue with installation on Linux with a new conda environment for p2ptrans. Kindly help me to figure out the issue. PFA screenshot.
![Screenshot 2023-07-18 221251](https://github.com/ftherrien/p2ptrans/assets/58852018/0ade5707-157f-47f7-9bca-d6b18ffbd1e6)

**Comment by ftherrien** [comment]
Hi @princego, what is the version of gcc on the computer you are using?
`gcc --version`

**Comment by princego** [comment]
> Hi @princego, what is the version of gcc on the computer you are using? `gcc --version`

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by ftherrien** [comment]
Hey @princego, sorry for the late reply. This is an 8 years old version of GCC, if you update to anything higher than 5 it should solve your problem.

If you are on a cluster/supercomputer this should just be a matter of calling a module, for example:

`module load gcc/11.3.0`

**Comment by princego** [comment]
Thanks for the reply. Unfortunately, the supercomputer does not have new GCC. It has Intel compilers instead.
version: `icc (ICC) 17.0.4 20170411`
How can I install using ICC?

**Comment by ftherrien** [comment]
Installing with ICC should be the same as using GCC, will close because this issue is old, but let me know if you need to reopen
