### ISSUE TITLE
numpy error, installation in conda env 

### ISSUE THREAD

**Issue by nityasagarjena** [ftherrien/p2ptrans#32]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
interpolation 2.2.4 requires packaging<22.0,>=21.3, but you have packaging 23.2 which is incompatible.
Successfully installed packaging-23.2
(myenv) [x_nitje@tetralith2 ~]$ p2ptrans -h
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
Traceback (most recent call last):
  File "/home/x_nitje/.conda/envs/myenv/bin/p2ptrans", line 6, in <module>
    from p2ptrans import *
  File "/home/x_nitje/.conda/envs/myenv/lib/python3.8/site-packages/p2ptrans/__init__.py", line 1, in <module>
    from . import fmodules
ImportError: numpy.core.multiarray failed to import

**Comment by ftherrien** [comment]
Hi, were you able to install it without errors? Did you solve #31? Seems like you maybe using a different environment then what you installed p2ptrans with.
