### ISSUE TITLE
p2ptrans does not work

### ISSUE THREAD

**Issue by vstevano** [ftherrien/p2ptrans#7]
Hi Félix,

The p2ptrans that I installed through pip, reports an error both when I try to do 
>> p2ptrans --help 
TypeError: bad operand type for unary -: '_Helper'

and when I try:

>> p2ptrans -I POSCAR_148 -F POSCAR_227
SyntaxError: invalid syntax

So, what is going on?

Thanks,
Vladan

**Comment by ftherrien** [comment]
Vladan,

p2ptrans is a unix command line tool so it should not be run inside python, but directly *at the command line*. 

You can also use p2ptrans as a python module and call different functions such as `p2ptrans.findMatching` and I will post more instructions about that soon!
